const test=require('node:test'),assert=require('node:assert/strict'),R=require('../js/racing/racing-rules.js');
function race(){const g=R.create({humans:[0,1,2,3,4,5]});g.phase='racing';g.cars.forEach((c,i)=>{const s=500-i*60,p=R.sample(s);Object.assign(c,{x:p.x,y:p.y,z:p.z,heading:p.heading,lastS:s,safe:s,progress:s,invulnerable:0});});return g;}
function ticks(g,n){for(let i=0;i<n;i++)R.step(g,1/60,{players:{}});}
test('两次 E 连放：首槽用完后第二槽补到第一槽',()=>{const g=race(),c=g.cars[1];c.inventory=['boost','shield'];R.useItem(g,c);assert.deepEqual(c.inventory,['shield',null]);assert.equal(c.slot,0);R.useItem(g,c);assert.ok(c.boost>0&&c.shield>0);assert.deepEqual(c.inventory,[null,null]);});
test('选择第二槽后消耗也压紧队列；失败不消耗或改动次序',()=>{const g=race(),c=g.cars[0];c.inventory=['missile','shield'];R.switchItem(g,c);R.useItem(g,c);assert.deepEqual(c.inventory,['missile',null]);assert.equal(c.slot,0);const before=[...c.inventory];assert.equal(R.useItem(g,c),false);assert.deepEqual(c.inventory,before);});
test('导弹道具与主炮冷却分开，连放两枚导弹',()=>{const g=race(),c=g.cars[1];c.inventory=['missile','missile'];c.cooldown=1;assert.ok(R.useItem(g,c));assert.ok(R.useItem(g,c));assert.equal(g.shots.filter(s=>s.owner===1).length,2);});
test('猎首导弹只锁第一名，不受普通导弹距离限制，第一名不可对自己使用',()=>{const g=race();g.cars[5].item='leader';assert.equal(R.useItem(g,g.cars[5]),true);assert.equal(g.threats[0].target,0);assert.equal(g.threats[0].kind,'leader');g.cars[0].item='leader';assert.equal(R.useItem(g,g.cars[0]),false);});
test('飞碟预警后吸起第一名，后移有限距离，复位不会取回旧进度',()=>{const g=race(),c=g.cars[0],before=c.progress;g.cars[5].item='ufo';assert.ok(R.useItem(g,g.cars[5]));ticks(g,90);assert.ok(c.lift>0);assert.equal(R.fire(g,c),false);ticks(g,180);assert.ok(c.progress<before-25&&c.progress>=before-50);const moved=c.progress;R.recover(g,c);assert.ok(c.progress<=moved+.01);assert.equal(c.lift,0);});
test('护盾可以在预警期间抵挡飞碟，同一目标不会被重复控制',()=>{const g=race(),c=g.cars[0];g.cars[5].item='ufo';R.useItem(g,g.cars[5]);g.cars[4].item='ufo';assert.equal(R.useItem(g,g.cars[4]),false);c.item='shield';R.useItem(g,c);ticks(g,90);assert.equal(c.lift,0);assert.equal(c.shield,0);assert.equal(g.threats.length,0);});
test('飞碟后移跨圈边界时同步 lap/safe/lastS，不碰已完赛车手',()=>{const g=race(),c=g.cars[0];c.progress=R.track.length+10;c.lastS=10;c.safe=c.progress;const p=R.sample(10);Object.assign(c,{x:p.x,y:p.y,z:p.z});g.cars[5].item='ufo';R.useItem(g,g.cars[5]);ticks(g,240);assert.equal(c.lap,0);assert.ok(c.safe<R.track.length);assert.ok(c.lastS<R.track.length);});
test('EMP 只影响范围内对手，护盾可挡，不伤自己',()=>{const g=race(),c=g.cars[1],near=g.cars[0],far=g.cars[2];Object.assign(near,{x:c.x+5,z:c.z,speed:30});far.speed=30;c.item='emp';assert.ok(R.useItem(g,c));assert.ok(near.speed<30);assert.equal(far.speed,30);assert.equal(c.stun,0);});
test('追赶道具按名次与距离分配，第一名不能抽到猎首和飞碟',()=>{assert.equal(typeof R.rollItem,'function');const g=race(),first=new Set(),last=new Set();for(let i=0;i<400;i++){first.add(R.rollItem(g,g.cars[0]));last.add(R.rollItem(g,g.cars[5]));}assert.ok(!first.has('ufo')&&!first.has('leader'));assert.ok(last.has('ufo')&&last.has('leader')&&last.has('emp'));});
test('飞碟在空中连续向后牵引，再落地，不在最后一帧瞬移',()=>{const g=race(),c=g.cars[0],before=c.progress;g.cars[5].item='ufo';R.useItem(g,g.cars[5]);ticks(g,132);assert.ok(c.lift>0);assert.ok(c.progress<before-10&&c.progress>before-40);});
