const test=require('node:test'),assert=require('node:assert/strict'),R=require('../js/racing/racing-rules.js');
function ready(){const g=R.create();g.phase='racing';g.cars.slice(1).forEach(c=>c.finished=true);const c=g.cars[0],p=R.sample(60);Object.assign(c,{x:p.x,z:p.z,lastS:60,progress:60,safe:60,heading:p.heading});return g;}
const tick=(g,n,input)=>{for(let i=0;i<n;i++)R.step(g,1/60,input);};
test('方向键瞄准独立于车身，松开保持炮口方向并限制俯仰',()=>{const g=ready(),c=g.cars[0],h=c.heading;tick(g,30,{aimYaw:1,aimPitch:1});assert.ok(c.aim>.2);assert.ok(c.pitch>0);assert.ok(Math.abs(c.heading-h)<1e-10);const a=c.aim;tick(g,30,{});assert.equal(c.aim,a);tick(g,300,{aimYaw:1,aimPitch:1});assert.ok(c.aim<=.75&&c.pitch<=.3);});
test('双槽切换不丢道具，E 对应规则只消耗选中槽',()=>{const g=ready(),c=g.cars[0];assert.deepEqual(c.inventory,[null,null]);c.item='boost';R.switchItem(g,c);c.item='shield';R.useItem(g,c);assert.equal(c.slot,0);assert.equal(c.item,'boost');R.useItem(g,c);assert.ok(c.boost>0);assert.deepEqual(c.inventory,[null,null]);});
test('两个槽位都满时不会吞掉赛道补给',()=>{const g=ready(),c=g.cars[0],p=g.pickups[0],s=R.sample(p.s);c.inventory=['boost','shield'];Object.assign(c,{x:s.x,z:s.z});R.step(g,1/60,{});assert.equal(p.cooldown,0);});
test('按住空格的规则射击受冷却限制，俯仰进入炮弹轨迹',()=>{const g=ready(),c=g.cars[0];c.pitch=.2;tick(g,60,{fire:true});assert.ok(g.shots.length>=1);assert.ok(g.shots.length<=2);assert.ok(g.shots[0].pitch>0);});
test('转向平滑，漂移产生侧滑，松开后恢复抓地',()=>{const g=ready(),c=g.cars[0];c.speed=30;tick(g,1,{throttle:1,steer:1,drift:true});assert.ok(c.steering>0&&c.steering<1);tick(g,22,{throttle:1,steer:1,drift:true});assert.ok(c.drifting);assert.ok(Math.abs(c.slip)>.1);const slip=Math.abs(c.slip);tick(g,30,{throttle:1});assert.ok(Math.abs(c.slip)<slip);assert.equal(c.drifting,false);});
test('低速打方向或按漂移不能原地刷漂移奖励',()=>{const g=ready(),c=g.cars[0];tick(g,120,{steer:1,drift:true});assert.equal(c.drifting,false);assert.equal(c.driftCharge,0);assert.equal(c.boost,0);});
test('复位清空侧滑、漂移蓄力和转向残量',()=>{const g=ready(),c=g.cars[0];c.slip=.5;c.steering=1;c.driftCharge=.8;c.drifting=true;R.recover(g,c);assert.equal(c.slip,0);assert.equal(c.steering,0);assert.equal(c.driftCharge,0);assert.equal(c.drifting,false);});
test('有效高速漂移出弯提供一次短推进，松开后不能重复领',()=>{const g=ready(),c=g.cars[0],p=R.sample(100);Object.assign(c,{x:p.x,z:p.z,heading:p.heading,lastS:100,progress:100,safe:100,speed:30});tick(g,90,{throttle:1,steer:.5,drift:true});assert.ok(c.driftCharge>=.6);tick(g,1,{throttle:1});assert.ok(c.boost>0);assert.equal(c.driftCharge,0);const boost=c.boost;tick(g,1,{throttle:1});assert.ok(c.boost<boost);});
test('当前槽已满时补给进入备用槽，保留当前选择',()=>{const g=ready(),c=g.cars[0],p=R.sample(g.pickups[0].s);c.item='boost';Object.assign(c,{x:p.x,z:p.z,lastS:p.s,progress:p.s,safe:p.s,seg:-1});R.step(g,1/60,{});assert.equal(c.item,'boost');assert.ok(c.inventory[1]);assert.equal(c.slot,0);});
