const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const out='output/mobile-v7.1.1';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true,args:['--use-angle=d3d11']});try{const context=await b.newContext({viewport:{width:844,height:390},userAgent:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/130.0.0.0 Mobile Safari/537.36',hasTouch:true,isMobile:true,deviceScaleFactor:1});const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8001/play/niuniu-tank/';
const cdp=await context.newCDPSession(p),touches=new Map();
async function hold(selector,id,dx,dy){const r=await p.locator(selector).boundingBox();assert.ok(r);touches.set(id,{id,x:r.x+r.width/2+dx,y:r.y+r.height/2+dy});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[...touches.values()]});}
async function up(selector,id){touches.delete(id);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[...touches.values()]});}
await p.goto(base+'classic.html');await p.waitForFunction(()=>window.classicReady);const before=JSON.parse(await p.evaluate(()=>render_game_to_text()));await hold('.drive',1,0,-40);await hold('.aim',2,40,0);await p.evaluate(()=>advanceTime(500));const after=JSON.parse(await p.evaluate(()=>render_game_to_text()));assert.notEqual(before.player.z,after.player.z);assert.ok(await p.evaluate(()=>MobileAim.active));await up('.drive',1);await up('.aim',2);assert.deepEqual(await p.evaluate(()=>MobileControls.held()),[]);await p.screenshot({path:out+'/classic-landscape.png'});await p.locator('[data-control="Escape"]').tap();assert.equal(await p.locator('#classicPause').isVisible(),true);await p.locator('#classicResume').tap();
await p.goto(base+'racing.html?autotest=1');await p.waitForFunction(()=>window.racingReady);await p.locator('#start').tap();await p.evaluate(()=>advanceTime(3300));await hold('.drive',3,0,-40);await hold('[data-control="Space"]',4,0,0);await p.evaluate(()=>advanceTime(700));assert.ok(JSON.parse(await p.evaluate(()=>render_game_to_text())).player.speed>0);await up('.drive',3);await up('[data-control="Space"]',4);await p.screenshot({path:out+'/racing-landscape.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:out+'/racing-portrait.png'});
await p.goto(base+'index.html');await p.waitForFunction(()=>document.querySelectorAll('.modeCard').length===3);await p.screenshot({path:out+'/menu-portrait.png'});await p.locator('.modeCard').nth(1).tap();await p.locator('[data-difficulty="normal"]').tap();await p.waitForFunction(()=>typeof state!=='undefined'&&state!==STATE.MENU);await p.setViewportSize({width:844,height:390});await p.locator('[data-control="KeyB"]').tap();await p.waitForTimeout(150);assert.ok(await p.locator('#cmdcard .cmdBtn').count()>0);await p.screenshot({path:out+'/survival-landscape.png'});
const cam=await p.evaluate(()=>({x:camFocus.x,z:camFocus.z}));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:8,x:430,y:160}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:8,x:480,y:180}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notDeepEqual(await p.evaluate(()=>({x:camFocus.x,z:camFocus.z})),cam);
await p.evaluate(()=>createFriendlyUnit('light',{x:0,z:20}));await p.locator('[data-control="TouchPlayer"]').tap();await p.locator('[data-control="TouchCommand"]').tap();await p.touchscreen.tap(420,180);assert.ok(await p.evaluate(()=>friendlyUnits.some(u=>u.moveTarget||u.attackTarget)));
const zoom=await p.evaluate(()=>camHeight);await p.locator('[data-control="Zoom＋"]').tap();assert.ok(await p.evaluate(()=>camHeight)<zoom);
await p.setViewportSize({width:390,height:844});await p.screenshot({path:out+'/survival-portrait.png'});assert.ok(await p.locator('#touchControls').isVisible());
await p.goto(base+'classic.html');await p.waitForFunction(()=>window.classicReady);await p.screenshot({path:out+'/classic-portrait.png'});
for(const ratio of [.75,2]){const c=await b.newContext({viewport:{width:667,height:375},userAgent:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/130.0.0.0 Mobile Safari/537.36',hasTouch:true,isMobile:true,deviceScaleFactor:ratio});const page=await c.newPage();await page.goto(base+'racing.html');await page.waitForFunction(()=>window.racingReady);const size=await page.evaluate(()=>({inner:innerWidth,canvas:document.querySelector('canvas').getBoundingClientRect().width,overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(size.inner,667);assert.equal(size.canvas,667);assert.equal(size.overflow,false);await c.close();}
console.log('mobile controls, portrait/landscape and DPR PASS');assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({classicMoved:true,multiTouchReleased:true,racingMoved:true,errors},null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
